plugins {
    id 'java-library'
    id 'maven-publish'
    id 'idea'
    id 'net.neoforged.moddev' version '2.0.141'
}

def ae2wtlibDependency = "curse.maven:applied-energistics-2-wireless-terminals-459929:7693114"
def extractedAe2wtlibApiJarDir = layout.buildDirectory.dir("tmp/ae2wtlibApiJar")
def ae2wtlibApiJarFiles = fileTree(extractedAe2wtlibApiJarDir.get().asFile) {
    include "*.jar"
}

version = mod_version
group = mod_group_id

repositories {
    mavenCentral()
    maven {
        url "https://cursemaven.com"
    }
}

base {
    archivesName = mod_id
}

java.toolchain.languageVersion = JavaLanguageVersion.of(21)

neoForge {
    version = project.neo_version

    runs {
        client {
            client()
            systemProperty 'neoforge.enabledGameTestNamespaces', project.mod_id
        }

        server {
            server()
            programArgument '--nogui'
            systemProperty 'neoforge.enabledGameTestNamespaces', project.mod_id
        }

        gameTestServer {
            type = "gameTestServer"
            systemProperty 'neoforge.enabledGameTestNamespaces', project.mod_id
        }

        data {
            data()
            programArguments.addAll '--mod', project.mod_id, '--all', '--output', file('src/generated/resources/').getAbsolutePath(), '--existing', file('src/main/resources/').getAbsolutePath()
        }

        configureEach {
            systemProperty 'forge.logging.markers', 'REGISTRIES'
            logLevel = org.slf4j.event.Level.DEBUG
            getAdditionalRuntimeClasspathConfiguration().dependencies.add(
                    project.dependencies.create("com.belerweb:pinyin4j:2.5.1")
            )
        }
    }

    mods {
        "${mod_id}" {
            sourceSet(sourceSets.main)
        }
    }
}

sourceSets.main.resources { srcDir 'src/generated/resources' }

configurations {
    ae2wtlibApiSource {
        transitive = false
    }
}

dependencies {
    implementation "com.belerweb:pinyin4j:2.5.1"
    jarJar "com.belerweb:pinyin4j:2.5.1"

    implementation "curse.maven:emi-580555:6420931"
    implementation "curse.maven:jei-238222:7420587"
    runtimeOnly "curse.maven:ae2-jei-integration-1074338:7727898"
    implementation "curse.maven:jade-324717:7545219"

    implementation "curse.maven:guideme-1173950:7127444"
    implementation "curse.maven:applied-energistics-2-223794:7027323"

    implementation "curse.maven:glodium-957920:5821676"
    implementation "curse.maven:ex-pattern-provider-892005:8025439"

    implementation "curse.maven:geckolib-388172:7707149"
    implementation "curse.maven:advancedae-1084104:7849217"

    compileOnly "curse.maven:ae2-crystal-science-1435174:8036407"
    runtimeOnly "curse.maven:ae2-crystal-science-1435174:8036407"
    compileOnly "curse.maven:ae2-lightning-tech-1527395:8036157"
    runtimeOnly "curse.maven:ae2-lightning-tech-1527395:8036157"

    compileOnly ae2wtlibDependency
    runtimeOnly ae2wtlibDependency
    compileOnly ae2wtlibApiJarFiles

    implementation "curse.maven:ldlib-626676:8030336"
    implementation "curse.maven:neo-eco-ae-extension-1460639:7884362"

    compileOnly "curse.maven:extendedae-plus-1337639:7960385"
    runtimeOnly "curse.maven:extendedae-plus-1337639:7960385"

    implementation "curse.maven:applied-flux-965012:7429565"

    implementation "curse.maven:applied-pneumatics-1355087:7723695"
    implementation "curse.maven:pneumaticcraft-repressurized-281849:7830507"

    implementation "curse.maven:applied-create-1474758:7945860"
    implementation "curse.maven:kotlin-for-forge-351264:7471280"
    implementation "curse.maven:create-328085:7963363"

    implementation "curse.maven:mega-cells-622112:7952621"
    implementation "curse.maven:cloth-config-348521:5729127"

    implementation "curse.maven:mekanism-268560:7904058"
    implementation "curse.maven:applied-mekanistics-574300:7096962"
    ae2wtlibApiSource ae2wtlibDependency
}

tasks.register("extractAe2wtlibApiJar", Sync) {
    from({
        zipTree(configurations.ae2wtlibApiSource.singleFile)
    }) {
        include "META-INF/jarjar/de.mari_023.ae2wtlib_api-*.jar"
        eachFile { details ->
            details.path = details.name
        }
        includeEmptyDirs = false
    }
    into(extractedAe2wtlibApiJarDir)
}

tasks.withType(JavaCompile).configureEach {
    dependsOn(tasks.named("extractAe2wtlibApiJar"))
}

var generateModMetadata = tasks.register("generateModMetadata", ProcessResources) {
    var replaceProperties = [minecraft_version      : minecraft_version,
                             minecraft_version_range: minecraft_version_range,
                             neo_version            : neo_version,
                             neo_version_range      : neo_version_range,
                             loader_version_range   : loader_version_range,
                             mod_id                 : mod_id,
                             mod_name               : mod_name,
                             mod_license            : mod_license,
                             mod_version            : mod_version,
                             mod_authors            : mod_authors,
                             mod_description        : mod_description]
    inputs.properties replaceProperties
    expand replaceProperties
    from "src/main/templates"
    into "build/generated/sources/modMetadata"
}

sourceSets.main.resources.srcDir generateModMetadata
neoForge.ideSyncTask generateModMetadata

publishing {
    publications {
        register('mavenJava', MavenPublication) {
            from components.java
        }
    }
    repositories {
        maven {
            url "file://${project.projectDir}/repo"
        }
    }
}

idea {
    module {
        downloadSources = true
        downloadJavadoc = true
    }
}
