dependencies {
    compileOnly(libs.jetbrains.annotations)

    testImplementation(libs.testframework)
    testImplementation(libs.junit.jupiter)
    testRuntimeOnly(libs.junit.platform.launcher)

    jarJar(api(forge.mdlib.get()))

    // Misc libraries
    compileOnly(forge.jech)
    compileOnly(forge.curios)

    // AE2
    accessCompileOnly(forge.ae2)
    testImplementation(forge.ae2)
    compileOnly(forge.guideme)
    compileOnly(forge.ae2wt)
    compileOnly(forge.ae2wt.api)

    // AE2 addons
    compileOnly(forge.eae)
    compileOnly(forge.aecs)
    compileOnly(forge.aelt)
    compileOnly(forge.aeltpp)
    compileOnly(forge.actually.additions)
    compileOnly(forge.applied.flux)
    compileOnly(forge.applied.create)
    compileOnly(forge.create)
    compileOnly(forge.mega.cells)
    compileOnly(forge.aae)
    compileOnly(forge.sut)
    compileOnly(forge.ae2ji)
    compileOnly(forge.amek)
    compileOnly(forge.mek)
    compileOnly(forge.eco)

    // FTB
    compileOnly(forge.ftbultimine)

    // Energy integrations
    compileOnly(forge.oritech)
    testImplementation(forge.oritech)

    // Recipe viewers
    compileOnly(forge.bundles.jei)
    compileOnly(forge.emi)

    // UI framework
    compileOnly(forge.ldlib)
    testImplementation(forge.ldlib)

    // WAILA-likes
    compileOnly(forge.jade)

    // Standard runtime mods
    localRuntime(forge.spark)
    localRuntime(forge.bhc)

    // FTB //
    localRuntime(forge.architectury)
    localRuntime(forge.ftblibrary)
    localRuntime(forge.ftbultimine)

    localRuntime(forge.jade)
    localRuntime(forge.curios)
    localRuntime(forge.modernfix)
    localRuntime(forge.worldedit)
    localRuntime(forge.guideme)
    localRuntime(forge.ae2)
    localRuntime(forge.ldlib)
    localRuntime(forge.glodium)
    localRuntime(forge.geckolib)
    localRuntime(forge.cloth.config)
    localRuntime(forge.pneumaticcraft)
    localRuntime(forge.kotlinforforge)
    localRuntime(forge.mek)
    extraLocalRuntime(forge.sut)

    // Runtime AE2 addons
    extraLocalRuntime(forge.ae2ji)
    extraLocalRuntime(forge.aeltpp)
    extraLocalRuntime(forge.actually.additions)
    extraLocalRuntime(forge.ae2wt)
    extraLocalRuntime(forge.eae)
    extraLocalRuntime(forge.aecs)
    extraLocalRuntime(forge.aelt)
    extraLocalRuntime(forge.applied.flux)
    extraLocalRuntime(forge.aae)
    extraLocalRuntime(forge.eco)
    extraLocalRuntime(forge.extendedae.plus)
    extraLocalRuntime(forge.applied.pneumatics)
    extraLocalRuntime(forge.mega.cells)
    extraLocalRuntime(forge.amek)

    // Runtime recipe viewers
    localRuntime(forge.emi)
    localRuntime(forge.jei.neoforge.impl)

    // Client-only runtime mods
    clientLocalRuntime(forge.jech)
    clientLocalRuntime(forge.ctm)
    clientLocalRuntime(forge.worldedit.cui.forge)
    jarJar(forge.ctm.get())
    clientLocalRuntime(forge.sodium)
    clientLocalRuntime(forge.iris)
    renderNurseCfg(libs.renderNurse)

    //////////////////////////////////////////////////////
    // Runtime mods for dev testing with unclean client //
    //////////////////////////////////////////////////////
}
