dependencies {
    compileOnly(libs.jetbrains.annotations)
    compileOnly(libs.jspecify)

    testImplementation(libs.testframework)
    testCompileOnly(libs.jspecify)
    testCompileOnly(forge.ae2)

    jarJar(api(forge.mdlib.get()))
    jarJar(api(libs.ojalgo.get()))
    jarJar(api(forge.configuration.get()))
    additionalRuntimeClasspath(libs.ojalgo)

    // Misc libraries
    compileOnly(forge.jech)
    compileOnly(forge.curios)

    // AE2
    accessCompileOnly(forge.ae2)
    compileOnly(forge.guideme)
    compileOnly(forge.ae2wt)
    compileOnly(forge.ae2wt.api)

    // AE2 addons
    compileOnly(forge.eae)
    compileOnly(forge.aecs)
    compileOnly(forge.actually.additions)
    compileOnly(forge.applied.flux)
    compileOnly(forge.applied.create)
    compileOnly(forge.mega.cells)
    compileOnly(forge.aae)
    compileOnly(forge.sut)
    compileOnly(forge.ae2ji)
    compileOnly(forge.ae2ct)
    compileOnly(forge.amek)
    compileOnly(forge.mek)
    compileOnly(forge.eco)
    compileOnly(forge.extendedae.plus)

    // FTB
    compileOnly(forge.ftbultimine)

    // Energy integrations
    compileOnly(forge.brandonscore)
    compileOnly(forge.oritech)
    compileOnly(forge.modern.industrialization)
    compileOnly(forge.grandpower)

    // Recipe viewers
    compileOnly(forge.bundles.jei)
    compileOnly(forge.emi)

    // UI framework
    compileOnly(forge.ldlib)

    // WAILA-likes
    compileOnly(forge.jade)

    // Standard runtime mods
    localRuntime(forge.spark)
    localRuntime(forge.bhc)

    // FTB //
    localRuntime(forge.architectury)
    localRuntime(forge.ftblibrary)
    localRuntime(forge.ftbultimine)

    localRuntime(forge.jade)
    localRuntime(forge.curios)
    localRuntime(forge.modernfix)
    localRuntime(forge.worldedit)
    localRuntime(forge.guideme)
    localRuntime(forge.ae2)
    localRuntime(forge.ldlib)
    localRuntime(forge.glodium)
    localRuntime(forge.geckolib)
    localRuntime(forge.cloth.config)
    localRuntime(forge.pneumaticcraft)
    localRuntime(forge.kotlinforforge)
    localRuntime(forge.mek)
    localRuntime(forge.oritech)
    localRuntime(forge.modern.industrialization)
    localRuntime(forge.grandpower)
    localRuntime(forge.brandonscore)
    localRuntime(forge.codechickenlib)
    localRuntime(forge.draconic.evolution)

    extraLocalRuntime(forge.sut)

    // Runtime AE2 addons
    extraLocalRuntime(forge.ae2ji)
    extraLocalRuntime(forge.ae2ct)
    extraLocalRuntime(forge.actually.additions)
    extraLocalRuntime(forge.ae2wt)
    extraLocalRuntime(forge.eae)
    extraLocalRuntime(forge.aecs)
    extraLocalRuntime(forge.applied.flux)
    extraLocalRuntime(forge.aae)
    extraLocalRuntime(forge.eco)
    extraLocalRuntime(forge.extendedae.plus)
    extraLocalRuntime(forge.applied.pneumatics)
    extraLocalRuntime(forge.mega.cells)
    extraLocalRuntime(forge.amek)

    // Runtime recipe viewers
    localRuntime(forge.emi)
    localRuntime(forge.jei.neoforge.impl)

    // Client-only runtime mods
    clientLocalRuntime(forge.jech)
    clientLocalRuntime(forge.ctm)
    clientLocalRuntime(forge.athena)
    clientLocalRuntime(forge.worldedit.cui.forge)
    jarJar(forge.ctm.get())
    clientLocalRuntime(forge.sodium)
    clientLocalRuntime(forge.iris)
    renderNurseCfg(libs.renderNurse)

    //////////////////////////////////////////////////////
    // Runtime mods for dev testing with unclean client //
    //////////////////////////////////////////////////////
}
