org.gradle.jvmargs = -Xmx6G
org.gradle.daemon = false
org.gradle.java.installations.auto-download=false
org.gradle.parallel = true
org.gradle.caching = true


mod_id = data_energistics
mod_name = Data_Energistics
mod_version = 2.0.0
mod_license = MIT (code only / 仅代码); resources/assets are All Rights Reserved (资源保留所有权利)
mod_description =
mod_url = https://github.com/fish1145/DataEnergistics
mod_issue_tracker = https://github.com/fish1145/DataEnergistics/issues
maven_group = com.fish_dan_.data_energistics
