org.gradle.jvmargs = -Xmx6G
org.gradle.daemon = false
org.gradle.java.installations.auto-download=false
org.gradle.parallel = true
org.gradle.caching = true


mod_id = data_energistics
mod_name = Data_Energistics
mod_version = 3.1.2
mod_license = AGPL-3.0-or-later (code); All Rights Reserved (resources/assets)
mod_description =
mod_url = https://github.com/fish1145/DataEnergistics
mod_issue_tracker = https://github.com/fish1145/DataEnergistics/issues
maven_group = com.fish_dan_.data_energistics
