package com.fish_dan_.data_energistics.ae2.key;

import com.fish_dan_.data_energistics.Data_Energistics;

import net.minecraft.network.chat.Component;
import net.minecraft.resources.ResourceLocation;

import com.mojang.serialization.Codec;
import com.mojang.serialization.MapCodec;

/**
 * Stateless AE resource generated by orbital observatories and consumed by orbital weapons.
 */
public final class CelestialEnergyKey extends DigitalizationKey {

    public static final ResourceLocation ID = ResourceLocation.fromNamespaceAndPath(Data_Energistics.MODID, "celestial_energy");
    public static final CelestialEnergyKey INSTANCE = new CelestialEnergyKey();
    public static final MapCodec<CelestialEnergyKey> MAP_CODEC = MapCodec.unit(INSTANCE);
    public static final Codec<CelestialEnergyKey> CODEC = MAP_CODEC.codec();

    private CelestialEnergyKey() {}

    public static CelestialEnergyKey of() {
        return INSTANCE;
    }

    @Override
    public ResourceLocation getId() {
        return ID;
    }

    @Override
    protected Component computeDisplayName() {
        return Component.translatable("key." + Data_Energistics.MODID + ".celestial_energy");
    }

    @Override
    public boolean equals(Object obj) {
        return obj instanceof CelestialEnergyKey;
    }

    @Override
    public int hashCode() {
        return ID.hashCode();
    }

    @Override
    public String toString() {
        return "CelestialEnergyKey{}";
    }
}
