package com.fish_dan_.data_energistics.ae2.key;

import com.fish_dan_.data_energistics.Data_Energistics;

import net.minecraft.network.chat.Component;
import net.minecraft.resources.ResourceLocation;

import com.mojang.serialization.Codec;
import com.mojang.serialization.MapCodec;

/**
 * Stateless AE resource generated by orbital observatories and consumed by orbital weapons.
 */
public final class StellarFluxKey extends DigitalizationKey {

    public static final ResourceLocation ID = ResourceLocation.fromNamespaceAndPath(Data_Energistics.MODID, "stellar_flux");
    public static final StellarFluxKey INSTANCE = new StellarFluxKey();
    public static final MapCodec<StellarFluxKey> MAP_CODEC = MapCodec.unit(INSTANCE);
    public static final Codec<StellarFluxKey> CODEC = MAP_CODEC.codec();

    private StellarFluxKey() {}

    public static StellarFluxKey of() {
        return INSTANCE;
    }

    @Override
    public ResourceLocation getId() {
        return ID;
    }

    @Override
    protected Component computeDisplayName() {
        return Component.translatable("key." + Data_Energistics.MODID + ".stellar_flux");
    }

    @Override
    public boolean equals(Object obj) {
        return obj instanceof StellarFluxKey;
    }

    @Override
    public int hashCode() {
        return ID.hashCode();
    }

    @Override
    public String toString() {
        return "StellarFluxKey{}";
    }
}
