package com.fish_dan_.data_energistics;

import net.neoforged.bus.api.SubscribeEvent;
import net.neoforged.fml.common.EventBusSubscriber;
import net.neoforged.fml.event.config.ModConfigEvent;
import net.neoforged.neoforge.common.ModConfigSpec;

@SuppressWarnings("removal")
@EventBusSubscriber(modid = Data_Energistics.MODID, bus = EventBusSubscriber.Bus.MOD)
public final class DataExtractorConfig {

    private static final ModConfigSpec.Builder BUILDER = new ModConfigSpec.Builder();

    private static final ModConfigSpec.IntValue BASE_DAMAGE = BUILDER
            .comment("Base damage dealt by the Data Extractor each cycle.")
            .defineInRange("baseDamage", 5, 0, Integer.MAX_VALUE);

    private static final ModConfigSpec.IntValue WORK_INTERVAL_SECONDS = BUILDER
            .comment("Seconds between each Data Extractor damage cycle before speed cards.")
            .defineInRange("workIntervalSeconds", 5, 1, Integer.MAX_VALUE);

    private static final ModConfigSpec.IntValue BASE_DATA_FLOW_PER_CYCLE = BUILDER
            .comment("Base data flow generated by the Data Extractor per cycle.")
            .defineInRange("baseDataFlowPerCycle", 100, 0, Integer.MAX_VALUE);

    private static final ModConfigSpec.IntValue DATA_FLOW_PER_SWORD_DAMAGE = BUILDER
            .comment("Additional data flow generated per point of sword/base damage.")
            .defineInRange("dataFlowPerSwordDamage", 20, 0, Integer.MAX_VALUE);

    private static final ModConfigSpec.IntValue BASE_TARGET_LIMIT = BUILDER
            .comment("Base maximum number of target mobs the Data Extractor can affect.")
            .defineInRange("baseTargetLimit", 20, 1, Integer.MAX_VALUE);

    private static final ModConfigSpec.IntValue TARGET_LIMIT_PER_CAPACITY_CARD = BUILDER
            .comment("Additional target limit granted by each installed capacity card.")
            .defineInRange("targetLimitPerCapacityCard", 5, 0, Integer.MAX_VALUE);

    private static final ModConfigSpec.DoubleValue EXTRA_TARGET_DATA_FLOW_MULTIPLIER = BUILDER
            .comment("Additional data flow multiplier per extra target. 0.25 = +25% per extra target.")
            .defineInRange("extraTargetDataFlowMultiplier", 0.25D, 0.0D, Double.MAX_VALUE);

    private static final ModConfigSpec.DoubleValue MOB_REQUIRED_DAMAGE = BUILDER
            .comment("Required total damage to complete a mob data carrier after a target is recorded.")
            .defineInRange("mobRequiredDamage", 1024.0D, 1.0D, Double.MAX_VALUE);

    private static final ModConfigSpec.ConfigValue<String> MOB_DATA_BLACKLIST = BUILDER
            .comment("Comma-separated entity ids that cannot be recorded into mob data carriers.")
            .define("mobDataBlacklist", "");

    private static final ModConfigSpec.DoubleValue ORE_REQUIRED_AMOUNT = BUILDER
            .comment("Required total ore amount to complete an ore data carrier.")
            .defineInRange("oreRequiredAmount", 4096.0D, 1.0D, Double.MAX_VALUE);

    private static final ModConfigSpec.ConfigValue<String> ORE_DATA_BLACKLIST = BUILDER
            .comment("Comma-separated item ids that cannot be recorded into ore data carriers.")
            .define("oreDataBlacklist", "");

    private static final ModConfigSpec.DoubleValue CROP_REQUIRED_AMOUNT = BUILDER
            .comment("Required total crop amount to complete a crop data carrier.")
            .defineInRange("cropRequiredAmount", 4096.0D, 1.0D, Double.MAX_VALUE);

    private static final ModConfigSpec.ConfigValue<String> CROP_DATA_BLACKLIST = BUILDER
            .comment("Comma-separated item ids that cannot be recorded into crop data carriers.")
            .define("cropDataBlacklist", "");

    private static final ModConfigSpec.ConfigValue<String> CROP_DATA_WHITELIST = BUILDER
            .comment("Comma-separated item ids additionally allowed in the Data Extractor crop slot, even if they do not match the built-in crop rules.")
            .define("cropDataWhitelist", "");

    private static final String DEFAULT_CROP_INPUT_MAPPINGS = "minecraft:wheat_seeds=minecraft:wheat@0.5,minecraft:beetroot_seeds=minecraft:beetroot@0.5," + "minecraft:melon=minecraft:melon@1.0,minecraft:melon_seeds=minecraft:melon@0.5,minecraft:melon_slice=minecraft:melon@0.5," + "minecraft:pumpkin=minecraft:pumpkin@1.0,minecraft:pumpkin_seeds=minecraft:pumpkin@0.5," + "minecraft:sweet_berries=minecraft:sweet_berries@1.0,minecraft:brown_mushroom=minecraft:brown_mushroom@1.0," + "minecraft:red_mushroom=minecraft:red_mushroom@1.0,minecraft:crimson_fungus=minecraft:crimson_fungus@1.0," + "minecraft:warped_fungus=minecraft:warped_fungus@1.0,minecraft:cactus=minecraft:cactus@1.0," + "minecraft:sugar_cane=minecraft:sugar_cane@1.0,minecraft:bamboo=minecraft:bamboo@1.0," + "minecraft:dandelion=minecraft:dandelion@1.0,minecraft:poppy=minecraft:poppy@1.0," + "minecraft:blue_orchid=minecraft:blue_orchid@1.0,minecraft:allium=minecraft:allium@1.0," + "minecraft:azure_bluet=minecraft:azure_bluet@1.0,minecraft:red_tulip=minecraft:red_tulip@1.0," + "minecraft:orange_tulip=minecraft:orange_tulip@1.0,minecraft:white_tulip=minecraft:white_tulip@1.0," + "minecraft:pink_tulip=minecraft:pink_tulip@1.0,minecraft:oxeye_daisy=minecraft:oxeye_daisy@1.0," + "minecraft:cornflower=minecraft:cornflower@1.0,minecraft:lily_of_the_valley=minecraft:lily_of_the_valley@1.0," + "minecraft:wither_rose=minecraft:wither_rose@1.0,minecraft:sunflower=minecraft:sunflower@1.0," + "minecraft:lilac=minecraft:lilac@1.0,minecraft:rose_bush=minecraft:rose_bush@1.0," + "minecraft:peony=minecraft:peony@1.0,minecraft:pink_petals=minecraft:pink_petals@1.0," + "minecraft:torchflower=minecraft:torchflower@1.0,minecraft:open_eyeblossom=minecraft:open_eyeblossom@1.0," + "minecraft:closed_eyeblossom=minecraft:closed_eyeblossom@1.0";
    private static final ModConfigSpec.ConfigValue<String> CROP_INPUT_MAPPINGS = BUILDER
            .comment("Comma-separated crop input mappings in the form input_item=recorded_crop@progress. Example: minecraft:wheat_seeds=minecraft:wheat@0.5")
            .define("cropInputMappings",
                    DEFAULT_CROP_INPUT_MAPPINGS);

    static final ModConfigSpec SPEC = BUILDER.build();

    public static int baseDamage = 5;
    public static int workIntervalSeconds = 5;
    public static int baseDataFlowPerCycle = 100;
    public static int dataFlowPerSwordDamage = 20;
    public static int baseTargetLimit = 20;
    public static int targetLimitPerCapacityCard = 5;
    public static double extraTargetDataFlowMultiplier = 0.25D;
    public static float mobRequiredDamage = 1024.0F;
    public static String mobDataBlacklist = "";
    public static float oreRequiredAmount = 4096.0F;
    public static String oreDataBlacklist = "";
    public static float cropRequiredAmount = 4096.0F;
    public static String cropDataBlacklist = "";
    public static String cropDataWhitelist = "";
    public static String cropInputMappings = DEFAULT_CROP_INPUT_MAPPINGS;

    private DataExtractorConfig() {}

    @SubscribeEvent
    static void onLoad(final ModConfigEvent event) {
        if (event.getConfig().getSpec() != SPEC) {
            return;
        }

        baseDamage = BASE_DAMAGE.get();
        workIntervalSeconds = WORK_INTERVAL_SECONDS.get();
        baseDataFlowPerCycle = BASE_DATA_FLOW_PER_CYCLE.get();
        dataFlowPerSwordDamage = DATA_FLOW_PER_SWORD_DAMAGE.get();
        baseTargetLimit = BASE_TARGET_LIMIT.get();
        targetLimitPerCapacityCard = TARGET_LIMIT_PER_CAPACITY_CARD.get();
        extraTargetDataFlowMultiplier = EXTRA_TARGET_DATA_FLOW_MULTIPLIER.get();
        mobRequiredDamage = MOB_REQUIRED_DAMAGE.get().floatValue();
        mobDataBlacklist = MOB_DATA_BLACKLIST.get();
        oreRequiredAmount = ORE_REQUIRED_AMOUNT.get().floatValue();
        oreDataBlacklist = ORE_DATA_BLACKLIST.get();
        cropRequiredAmount = CROP_REQUIRED_AMOUNT.get().floatValue();
        cropDataBlacklist = CROP_DATA_BLACKLIST.get();
        cropDataWhitelist = CROP_DATA_WHITELIST.get();
        cropInputMappings = CROP_INPUT_MAPPINGS.get();
    }
}
