package com.fish_dan_.data_energistics.blockentity.machine.mimetic;

import net.minecraft.world.item.ItemStack;

import appeng.api.stacks.AEItemKey;

import java.util.Collections;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;

/**
 * Component-sensitive mimetic output kept as counts instead of expanded item-stack copies.
 *
 * <p>
 * A value represents one complete generated batch. Its insertion-ordered map is immutable, contains only positive
 * balances and can therefore be passed directly to AE storage or the pending-output ledger without materialization.
 * </p>
 *
 * @param items      generated item counts keyed by item and data components
 * @param experience generated experience count
 */
public record MimeticGeneratedOutput(Map<AEItemKey, Long> items, long experience) {

    private static final MimeticGeneratedOutput EMPTY = new MimeticGeneratedOutput(Map.of(), 0L);

    public MimeticGeneratedOutput {
        LinkedHashMap<AEItemKey, Long> copy = new LinkedHashMap<>(items.size());
        for (Map.Entry<AEItemKey, Long> entry : items.entrySet()) {
            long amount = entry.getValue();
            if (amount <= 0L) {
                throw new IllegalArgumentException("Mimetic generated-item amounts must be positive");
            }
            copy.merge(entry.getKey(), amount, Math::addExact);
        }
        if (experience < 0L) {
            throw new IllegalArgumentException("Mimetic generated experience cannot be negative");
        }
        items = Collections.unmodifiableMap(copy);
    }

    /**
     * Creates an empty generated batch.
     *
     * @return shared-state-free empty value
     */
    public static MimeticGeneratedOutput empty() {
        return EMPTY;
    }

    /**
     * Aggregates component-preserving stack counts into one generated batch.
     *
     * @param stacks generated stacks; empty entries are ignored
     * @return immutable compact output
     */
    public static MimeticGeneratedOutput fromStacks(List<ItemStack> stacks) {
        return fromStacks(stacks, 0L);
    }

    /**
     * Aggregates component-preserving stack counts and experience into one generated batch.
     *
     * @param stacks     generated stacks; empty entries are ignored
     * @param experience non-negative experience count
     * @return immutable compact output
     */
    public static MimeticGeneratedOutput fromStacks(List<ItemStack> stacks, long experience) {
        return new Accumulator().addStacks(stacks).addExperience(experience).build();
    }

    /**
     * Reports whether this batch contains neither items nor experience.
     *
     * @return {@code true} for an empty batch
     */
    public boolean isEmpty() {
        return this.items.isEmpty() && this.experience == 0L;
    }

    /**
     * Combines two generated batches while preserving the first-seen item order.
     *
     * @param other batch generated by the same work cycle
     * @return combined immutable output
     */
    public MimeticGeneratedOutput merge(MimeticGeneratedOutput other) {
        if (other.isEmpty()) {
            return this;
        }
        if (isEmpty()) {
            return other;
        }

        LinkedHashMap<AEItemKey, Long> merged = new LinkedHashMap<>(this.items);
        other.items.forEach((key, amount) -> merged.merge(key, amount, Math::addExact));
        return new MimeticGeneratedOutput(merged, saturatedAdd(this.experience, other.experience));
    }

    /**
     * Scales one sampled result to a number of logical rolls without creating repeated stacks.
     *
     * @param repetitions non-negative repetition count
     * @return scaled immutable output
     */
    public MimeticGeneratedOutput repeat(int repetitions) {
        if (repetitions < 0) {
            throw new IllegalArgumentException("repetitions cannot be negative");
        }
        if (repetitions == 0 || isEmpty()) {
            return empty();
        }
        if (repetitions == 1) {
            return this;
        }

        LinkedHashMap<AEItemKey, Long> repeated = new LinkedHashMap<>(this.items.size());
        this.items.forEach((key, amount) -> repeated.put(key, Math.multiplyExact(amount, repetitions)));
        return new MimeticGeneratedOutput(repeated, saturatedMultiply(this.experience, repetitions));
    }

    /**
     * Returns the total generated item count, saturating only when it cannot be represented by a {@code long}.
     *
     * @return non-negative item count
     */
    public long itemAmount() {
        long total = 0L;
        for (long amount : this.items.values()) {
            total = saturatedAdd(total, amount);
        }
        return total;
    }

    /**
     * Creates a mutable cycle-local accumulator for many independently rolled results.
     *
     * @return empty accumulator
     */
    public static Accumulator accumulator() {
        return new Accumulator();
    }

    /**
     * Aggregates repeated loot rolls without allocating an immutable map after every roll.
     */
    public static final class Accumulator {

        private final LinkedHashMap<AEItemKey, Long> items = new LinkedHashMap<>();
        private long experience;

        /**
         * Adds component-preserving stacks once.
         *
         * @param stacks generated stacks; empty entries are ignored
         * @return this accumulator
         */
        public Accumulator addStacks(List<ItemStack> stacks) {
            return addRepeatedStacks(stacks, 1);
        }

        /**
         * Adds the same fixed stack outputs for multiple logical rolls without copying them.
         *
         * @param stacks      generated stacks; empty entries are ignored
         * @param repetitions non-negative repetition count
         * @return this accumulator
         */
        public Accumulator addRepeatedStacks(List<ItemStack> stacks, int repetitions) {
            if (repetitions < 0) {
                throw new IllegalArgumentException("repetitions cannot be negative");
            }
            if (repetitions == 0) {
                return this;
            }
            for (ItemStack stack : stacks) {
                if (stack.isEmpty()) {
                    continue;
                }

                var key = AEItemKey.of(stack);
                if (key == null) {
                    throw new IllegalArgumentException("Non-empty mimetic output stack has no AE item key");
                }
                long amount = Math.multiplyExact((long) stack.getCount(), repetitions);
                this.items.merge(key, amount, Math::addExact);
            }
            return this;
        }

        /**
         * Adds another compact generated result.
         *
         * @param output generated result
         * @return this accumulator
         */
        public Accumulator add(MimeticGeneratedOutput output) {
            output.items.forEach((key, amount) -> this.items.merge(key, amount, Math::addExact));
            this.experience = saturatedAdd(this.experience, output.experience);
            return this;
        }

        /**
         * Adds a compact output for multiple logical rolls without creating intermediate maps.
         *
         * @param output      generated result for one roll
         * @param repetitions non-negative repetition count
         * @return this accumulator
         */
        public Accumulator addRepeated(MimeticGeneratedOutput output, int repetitions) {
            if (repetitions < 0) {
                throw new IllegalArgumentException("repetitions cannot be negative");
            }
            if (repetitions == 0 || output.isEmpty()) {
                return this;
            }
            output.items.forEach((key, amount) -> this.items.merge(
                    key,
                    Math.multiplyExact(amount, repetitions),
                    Math::addExact));
            this.experience = saturatedAdd(
                    this.experience,
                    saturatedMultiply(output.experience, repetitions));
            return this;
        }

        /**
         * Adds non-negative experience.
         *
         * @param amount experience count
         * @return this accumulator
         */
        public Accumulator addExperience(long amount) {
            if (amount < 0L) {
                throw new IllegalArgumentException("Mimetic generated experience cannot be negative");
            }
            this.experience = saturatedAdd(this.experience, amount);
            return this;
        }

        /**
         * Freezes the accumulated counts.
         *
         * @return immutable generated output
         */
        public MimeticGeneratedOutput build() {
            return new MimeticGeneratedOutput(this.items, this.experience);
        }
    }

    private static long saturatedAdd(long left, long right) {
        return right > 0L && left > Long.MAX_VALUE - right ? Long.MAX_VALUE : left + right;
    }

    private static long saturatedMultiply(long left, long right) {
        if (left <= 0L || right <= 0L) {
            return 0L;
        }
        return left > Long.MAX_VALUE / right ? Long.MAX_VALUE : left * right;
    }
}
